package com.likai.sshDemo.entity;
// Generated 2016-8-20 13:58:54 by Hibernate Tools 4.3.4.Final

/**
 * School generated by hbm2java
 */
public class School implements java.io.Serializable {

	private Integer schoolId;
	private String schoolName;
	private int province;
	private int city;
	private int area;
	private String gradePeriod;
	private boolean status;

	public School() {
	}

	public School(String schoolName, int province, int city, int area, String gradePeriod, boolean status) {
		this.schoolName = schoolName;
		this.province = province;
		this.city = city;
		this.area = area;
		this.gradePeriod = gradePeriod;
		this.status = status;
	}

	public Integer getSchoolId() {
		return this.schoolId;
	}

	public void setSchoolId(Integer schoolId) {
		this.schoolId = schoolId;
	}

	public String getSchoolName() {
		return this.schoolName;
	}

	public void setSchoolName(String schoolName) {
		this.schoolName = schoolName;
	}

	public int getProvince() {
		return this.province;
	}

	public void setProvince(int province) {
		this.province = province;
	}

	public int getCity() {
		return this.city;
	}

	public void setCity(int city) {
		this.city = city;
	}

	public int getArea() {
		return this.area;
	}

	public void setArea(int area) {
		this.area = area;
	}

	public String getGradePeriod() {
		return this.gradePeriod;
	}

	public void setGradePeriod(String gradePeriod) {
		this.gradePeriod = gradePeriod;
	}

	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
