package com.likai.sshDemo.entity;
// Generated 2016-8-20 13:58:54 by Hibernate Tools 4.3.4.Final

/**
 * Region generated by hbm2java
 */
public class Region implements java.io.Serializable {

	private Integer regionId;
	private String regionName;
	private int parentId;
	private boolean regionType;
	private boolean status;

	public Region() {
	}

	public Region(String regionName, int parentId, boolean regionType, boolean status) {
		this.regionName = regionName;
		this.parentId = parentId;
		this.regionType = regionType;
		this.status = status;
	}

	public Integer getRegionId() {
		return this.regionId;
	}

	public void setRegionId(Integer regionId) {
		this.regionId = regionId;
	}

	public String getRegionName() {
		return this.regionName;
	}

	public void setRegionName(String regionName) {
		this.regionName = regionName;
	}

	public int getParentId() {
		return this.parentId;
	}

	public void setParentId(int parentId) {
		this.parentId = parentId;
	}

	public boolean isRegionType() {
		return this.regionType;
	}

	public void setRegionType(boolean regionType) {
		this.regionType = regionType;
	}

	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
