package com.likai.sshDemo.entity;
// Generated 2016-8-20 13:58:54 by Hibernate Tools 4.3.4.Final

/**
 * SystemUserRole generated by hbm2java
 */
public class SystemUserRole implements java.io.Serializable {

	private Long id;
	private SystemRole systemRole;
	private SystemUser systemUser;

	public SystemUserRole() {
	}

	public SystemUserRole(SystemRole systemRole, SystemUser systemUser) {
		this.systemRole = systemRole;
		this.systemUser = systemUser;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public SystemRole getSystemRole() {
		return this.systemRole;
	}

	public void setSystemRole(SystemRole systemRole) {
		this.systemRole = systemRole;
	}

	public SystemUser getSystemUser() {
		return this.systemUser;
	}

	public void setSystemUser(SystemUser systemUser) {
		this.systemUser = systemUser;
	}

}
